---
driver:
  name: azurerm
  subscription_id: 'a4973a08-b04b-4dc8-a441-24a0b75dce60'
  location: canadaeast
  machine_size: Standard_B1s

transport:
  ssh_key: ~/.ssh/kitchen_id

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 13.8.5

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image_urn: Canonical:UbuntuServer:16.04-LTS:16.04.201807240
      vm_name: kitchen-ubuntu-vm

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
